sudo: required
services:
  - docker

before_install:
  - docker build -t felipearomani/docker-react -f Dockerfile.dev .

script:
  - docker run felipearomani/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-romani
  env: DockerRomani-env
  bucket_name: elasticbeanstalk-us-west-2-769177069788
  bucket_path: docker-romani
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY